### ISSUE TITLE
Property "text" does not exist in type

### ISSUE THREAD

**Issue by Kifoxive** [rajinwonderland/react-code-blocks#105]
Hello, I ran into a problem where the most important attribute `text` seems to be missing. In practice, everything works, but there is a problem with types. I am using Typescript

<img width="1023" alt="missing text" src="https://github.com/rajinwonderland/react-code-blocks/assets/75488758/86c26408-a900-4315-b84e-596c5018b1b7">

**Comment by ahsankhan26** [comment]
+1

**Comment by realvandi** [comment]
+1

**Comment by Husain010** [comment]
+1

**Comment by kleysonfiretail** [comment]
+1

**Comment by Renetnielsen** [comment]
+1

**Comment by Tealow2610** [comment]
Using it this way works for me 👍

const codeBlockProps = {
      text: line,
      language: language,
      showLineNumbers: false,
      theme: dracula
    };

    return (
      <CodeBlock {...codeBlockProps} />
    )

**Comment by thomasmost** [comment]
Lol, that's quite a whoopsie — sorry about the delay, fixed in 0.1.4

**Comment by rahulthewall** [comment]
Hello, I still have this issue with 0.1.4. Please let me know what details I can provide.
